version: '3'

volumes:
  kong-dbvol:

networks:
  kong-net:
    external: true

services:
  kong-db:
    image: postgres:9.6
    restart: always
    networks:
      kong-net:
        aliases:
          - kong-db
    volumes:
      - kong-dbvol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=kong

  kong-migrations:
    image: kong:latest
    restart: always
    networks:
      kong-net:
        aliases:
          - kong-migrations
    entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=admin
      - KONG_PG_PASSWORD=changeme
    depends_on:
      - kong-db

  kong:
    image: kong:latest
    restart: always
    networks:
      kong-net:
        aliases:
          - kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=admin
      - KONG_PG_PASSWORD=changeme
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
    ports:
      - 8001:8001
      - 8000:8000
    depends_on:
      - kong-migrations
      - kong-db
