version: '3'

volumes:
  kongmon-grafana-storage:

networks:
  kong-net:
    external: true

services:
  kongmon-grafana:
    image: ketitik/grafana:dev
    ports:
      - 3000:3000
    volumes:
      - kongmon-grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_SERVER_ROOT_URL=http://192.168.1.103:8000/grafana-test
    networks:
      kong-net: 
        aliases:
          - kongmon-grafana
    restart: always
