version: '3'

volumes:
  kongmon-influxdb-storage:
  kongmon-grafana-storage:

networks:
  kong-net:
    external: true

services:
  kongmon-influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - kongmon-influxdb-storage:/var/lib/influxdb
    environment:  
      - INFLUXDB_DB=dummydata
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=changeme
    networks:
      kong-net: 
        aliases:
          - kongmon-influxdb
    restart: always

  kongmon-grafana:
    image: ketitik/grafana:dev
    ports:
      - 3000:3000
    volumes:
      - kongmon-grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_SERVER_ROOT_URL=http://192.168.1.103:8000/grafana-test
    networks:
      kong-net: 
        aliases:
          - kongmon-grafana
    restart: always

  kongmon-telegraf:
    image: telegraf
    ports:
      - 8125:8125
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      kong-net: 
       aliases:
          - kongmon-telegraf
    restart: always
